name: Main Branch Validation

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  main-validation:
    name: main-validation
    uses: ./.github/workflows/validation.yml
