name: Pull Request Validation

on:
  pull_request:
    branches:
      - main
      - production
  workflow_dispatch:

permissions:
  contents: read

jobs:
  pr-validation:
    name: pr-validation
    uses: ./.github/workflows/validation.yml
